import { addIcon } from "obsidian";

/**
 * Two leaves and a bud — the tea plucking standard, and the project mark.
 * Generated by textures/mark.py; Obsidian wraps this in viewBox 0 0 100 100.
 */
export const DARJEELING_ICON = "darjeeling-leaf";
export const DARJEELING_TEA_STONE_ICON = "darjeeling-tea-stone";
export const DARJEELING_ICON_SVG =
  '<defs><linearGradient id="djLeafGradL" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="#86EFAC"/><stop offset="100%" stop-color="#15803D"/></linearGradient><linearGradient id="djLeafGradR" x1="1" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#86EFAC"/><stop offset="100%" stop-color="#15803D"/></linearGradient></defs><g id="blooming-leaves"><path d="M 50 78 C 22 84 2 64 8 44 C 22 42 38 56 50 78 Z" fill="url(#djLeafGradL)" opacity="0.95"/><path d="M 50 78 C 78 84 98 64 92 44 C 78 42 62 56 50 78 Z" fill="url(#djLeafGradR)" opacity="0.95"/><path d="M 50 75 C 32 72 20 54 28 34 C 40 40 46 56 50 75 Z" fill="#22C55E"/><path d="M 50 75 C 68 72 80 54 72 34 C 60 40 54 56 50 75 Z" fill="#22C55E"/><path d="M 50 78 C 40 82 32 85 28 89 C 42 93 58 93 72 89 C 68 85 60 82 50 78 Z" fill="#166534"/><path d="M 50 82 L 50 96" stroke="#166534" stroke-width="4.5" stroke-linecap="round"/></g><g id="amber-crystal" transform="translate(13.5, 4) scale(0.73)"><path fill="#FDE047" d="M51.8 0L54.5 0.2L56.1 2L57.4 5.1L57.4 8.4L49.6 26.4L47.3 35L47.3 46.3L50 56.1L38.9 58.2L33.8 47.9L24 36.1L24 34.6L26.8 21.3L48.4 1.6L51.6 0.2Z"/><path fill="#F59E0B" d="M62.1 7.8L76.4 26.2L77.3 38.7L79.3 46.9L88.7 62.5L87.7 65.8L80.7 77L76.2 68.8L69.7 61.7L63.1 57.8L55.1 56.1L54.7 55.3L52 45.9L51.8 36.9L53.9 28.1L60.2 15L62.1 8Z"/><path fill="#D97706" d="M23 41.4L28.3 47.9L33.2 56.4L36.5 68.6L35.5 80.3L33.8 85.4L30.1 91.6L12.1 73L11.1 70.3L11.5 67.2L23 41.6Z"/><path fill="#B45309" d="M50.8 60.5L57.4 60.9L63.5 63.1L70.3 68.8L74 73.8L77.5 82.2L74.2 94.3L72.5 97.3L69.7 99.2L65.8 99.8L48.4 95.1L34.2 93.9L38.5 86.1L40.6 78.7L41.2 69.1L40.2 62.5L50.6 60.7Z"/></g>';
export const DARJEELING_TEA_STONE_SVG = DARJEELING_ICON_SVG;

export function registerIcons(): void {
  addIcon(DARJEELING_ICON, DARJEELING_ICON_SVG);
  addIcon(DARJEELING_TEA_STONE_ICON, DARJEELING_TEA_STONE_SVG);
}
